name: CI - Feature, Bugfix and Hotfix Validation

on:
  push:
    branches:
      - 'feature/**'
      - 'bugfix/**'
      - 'hotfix/**'

  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # 1. Baixa o código
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Instala .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
      
      # 3. Restore
      - name: Restore dependencies
        run: dotnet restore FiapCloudGames.Catalog.slnx
        working-directory: src

      # 4. Build
      - name: Build solution
        run: dotnet build FiapCloudGames.Catalog.slnx --no-restore --configuration Release
        working-directory: src

      # 5. Testes
      - name: Run unit tests
        run: dotnet test FiapCloudGames.Catalog.slnx --configuration Release
        working-directory: src
