name: CD - Release

on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish-image:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src

    env:
      AWS_REGION: ${{ vars.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
      ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
      IMAGE_TAG: ${{ github.ref_name }}

    steps:
      # Checkout
      - name: Checkout code
        uses: actions/checkout@v4              

      # Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      # Restore
      - name: Restore dependencies
        run: dotnet restore FiapCloudGames.Catalog.slnx

      # Build
      - name: Build solution
        run: dotnet build FiapCloudGames.Catalog.slnx --configuration Release --no-restore

      # Testes
      - name: Run tests
        run: >
          dotnet test
          FiapCloudGames.Catalog.Tests/FiapCloudGames.Catalog.Tests.csproj
          --configuration Release
          --no-build

      # Configura credenciais da AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      # Login no Amazon ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Show repository structure
        run: |
          pwd
          ls -la
          echo ""
          echo "----- src -----"
          ls -la src || true
          echo ""
          echo "----- docker -----"
          ls -la docker || true

      # Build da imagem Docker
      - name: Build Docker Image
        working-directory: .
        run: |
          docker build \
            -f docker/Dockerfile \
            -t $ECR_REPOSITORY:$IMAGE_TAG \
            -t $ECR_REPOSITORY:latest \
            .

      # Tag da imagem para o ECR
      - name: Tag Docker Image
        run: |
          docker tag \
            $ECR_REPOSITORY:$IMAGE_TAG \
            $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

          docker tag \
            $ECR_REPOSITORY:latest \
            $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:latest

      # Publica as imagens no Amazon ECR
      - name: Push Docker Images
        run: |
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:latest
